### ISSUE TITLE
Submission problem statement

### ISSUE THREAD

**Issue by LesleyWheat** [LesleyWheat/CAS741_CEWS#1]

**Comment by smiths** [comment]
My feedback is as follows:
- in the future please create a link to the artifact to be reviewed
- put the citations before the period (the spacing looks odd with citations after the period.)
- is the type of the input a (nonsquare) matrix of real numbers?
- requiring Windows for the environment seems to be an overconstraint.  Can the environment be changed to include MacOS and Linux?  This would also be much more convenient for grading.  :smile:

I'll approve this project, and close this issue, but please think about the above points.
