### ISSUE TITLE
SRS: unambiguous characteristic of intended readers

### ISSUE THREAD

**Issue by joedf** [LesleyWheat/CAS741_CEWS#18]
> The reader should have a good understanding of classification (graduate level) and a base understanding of data analysis, machine learning and statistics.

Is there an example course name for "graduate level" classification? or did you mean graduate level for everything listed (data analysis, machine learning and statistics)? Sorry if I am missing something here... 😅

Or perhaps to be less ambiguous you could say "**data** classification"?

**Comment by LesleyWheat** [comment]
@joedf There are no graduate courses available (that I know of, in this department) for just classification and the graduate "intro to machine learning" course does not cover the required material so I don't actually have a course code for this. Such a course would effectively have the pre reqs of undergrad course knowledge of data analysis/machine learning/statistics. I don't actually think a course is required for this, I know people that have not taken a course and just have experience/reading of classification with a stats/ML course and they would be able to understand the content.

**Comment by joedf** [comment]
Ahh okay, so just general familiarity with ML related classification right? sounds to me!

**Comment by LesleyWheat** [comment]
Closed, added clarification to section.
