### ISSUE TITLE
SRS: provide simple reason of why no system constraints

### ISSUE THREAD

**Issue by joedf** [LesleyWheat/CAS741_CEWS#19]
I think I can understand why there are no system constraints, but it could be explicitly stated... maybe a short simple sentence?

This is according to the [SRS-Checklist.pdf](https://github.com/LesleyWheat/CAS741_CEWS/blob/main/docs/Checklists/SRS-Checklist.pdf):
> System constraints have an appropriate rationale (a constraint
**without a reason** for that constraint is likely making the SRS less
abstract than it should be)

Unless, I got that wrong... 😅

**Comment by LesleyWheat** [comment]
This does not make sense. You need a reason to create a system constraint, not to not a have a system constraint.

**Comment by joedf** [comment]
ahh okay :|
