### ISSUE TITLE
Comments over MG Document

### ISSUE THREAD

**Issue by DeeshaPatel** [LesleyWheat/CAS741_CEWS#33]
- [ ] Your AC2 provides low information content phrases. 
- [ ] 1 Anticipated change should have associated with only 1 module. If you are assign multiple modules to the single associated changes you should explicitly give the reasons behind it. 
- [ ] Control module is handling all 3 module excluding graph module. I don't seems the same in your table 2
- [x] Your 3rd reference in bibliography don't have author name? 
- [ ] Not supper important but your Uses hierarchy should have light arrows. 
- [x] Your R2 don't have information about graph but you mention in your table 2. Inconsistency. 
- [x] At least introduce your Software Decision Hiding modules in MG. 

This is all for MG.

**Comment by LesleyWheat** [comment]
> Your 3rd reference in bibliography don't have author name?

Author 1, ref 1
longdash, ref 2

Just means the same author for 1 and 2.

**Comment by LesleyWheat** [comment]
> Your R2 don't have information about graph but you mention in your table 2. Inconsistency.

R2 preforms the calculation which requires the computation of the graph. Covered in SRS.

**Comment by LesleyWheat** [comment]
> Your AC2 provides low information content phrases.

? What more information do you want? There isn't much to say on OS changes.

**Comment by LesleyWheat** [comment]
> 1 Anticipated change should have associated with only 1 module. If you are assign multiple modules to the single associated changes you should explicitly give the reasons behind it.

Added: 8.1 Explanation of Anticipated changes impacting multiple modules
• AC3: Additional input options would be passed through M2 and validated by M3 then
implemented by M6.
• AC4: Additional input options would be passed through M2 and validated by M3 then
implemented by M6.
• AC5: GPU use indicates a hardware change, impacting M1, and it may require a
change in the algorithm used by M6 so it is optimized for GPU use.
• AC7: Additional input options would be passed through M2 then processed by M3.

**Comment by LesleyWheat** [comment]
> At least introduce your Software Decision Hiding modules in MG.

I have no Software Decision Hiding modules
