### ISSUE TITLE
Comments over MIS document

### ISSUE THREAD

**Issue by DeeshaPatel** [LesleyWheat/CAS741_CEWS#34]
- [ ] Missing information like transition, input, exceptions in section 6. check for all the Modules. 
- [x] Output should written as out := 
- [ ] TypeError is checked by the programming language. You can just mention the type in the input. 
- [ ] Input Module takes input from where? In other words, it should take from file or terminal. So, there should be some environment variable. 
- [x] In output Module, it looks like you have input of J_n but not mention it in Access Routines. 
- [ ] Think about exception in calculation module. 
- [ ] Missing symbols description of C_i, V_ij and many more. 
- [x] Hard to read equation in calcCEWS(). It's good to break in different lines. 
- [ ] Which module uses Hardware Hiding Module? 
- [ ] Graph Module don't have environment variable? Because every graph deals with the Screen. 
- [ ] It's good to order your Modules 
- [x] I guess matrix notation, have alphabet x instead of symbol of multiplication (\times). 
- [ ] Not super important but may be it is not good idea to write links directly in the document. You should use \href or \ref. 

This is all for MIS document.

**Comment by LesleyWheat** [comment]
> TypeError is checked by the programming language. You can just mention the type in the input.

My type checking will likely be more restrictive than the programming language's. Also languages do not preform type checking in every case (passing by reference/pointers, interpreted language before runtime, etc) and you can usually pass data as undefined type as well.

**Comment by LesleyWheat** [comment]
> Output should written as out :=

From the template: "For instance, the symbol := is used for a multiple assignment statement...". I am not using multiple assignment statements.

**Comment by LesleyWheat** [comment]
> Input Module takes input from where? In other words, it should take from file or terminal. So, there should be some environment variable.

The input module does not interact with any files or the terminal. inData and inLabels are passed from the Control Module. If passed by value (as they should be but for practical reasons, likely not) then they are copied onto the stack and don't map to anything outside the program.

**Comment by LesleyWheat** [comment]
> Think about exception in calculation module.

? What does this mean?

**Comment by LesleyWheat** [comment]
> Missing symbols description of C_i, V_ij and many more.

They are in the SRS as said in Section 2.

**Comment by LesleyWheat** [comment]
> Which module uses Hardware Hiding Module?

All of them imo (anything where you aren't directly using hardware memory addresses is using the OS but this course doesn't seem to acknowledge that) so probably none of them for the purpose of this assignment (or maybe control?).

**Comment by LesleyWheat** [comment]
> Graph Module don't have environment variable? Because every graph deals with the Screen

? Not sure what you're trying to say here because Graph doesn't have anything to do with the screen?

**Comment by DeeshaPatel** [comment]
> > Output should written as out :=
> 
> From the template: "For instance, the symbol := is used for a multiple assignment statement...". I am not using multiple assignment statements.

https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/A3/A3P1_Spec.pdf -- check this example.

**Comment by DeeshaPatel** [comment]
> passed by value

I see. It's perfect. But I think you should mention what kind of environment variable is. I mean what inData and inLabels are? Those are files?

**Comment by DeeshaPatel** [comment]
> 

I am not sure but the calculation module can generate some kind of exceptions.

**Comment by DeeshaPatel** [comment]
> Sec

I have checked your [SRS ](https://github.com/LesleyWheat/CAS741_CEWS/blob/393f285cd50da669a90f6eda17f61ee7b2faaf89/docs/SRS/SRS.pdf) page no -> iii -> Section 1.2 Table of symbols. But I don't find it there. Probably I am wrong.

**Comment by DeeshaPatel** [comment]
> 

I see. As per your MG, your Graph module constructs the graph at the end. Even your MIS transition phase says that it will construct a graph. So, how are you going to show it at the end? If you are exporting your graph to the system then the File can be an Environment variable and if you are going to show your graph to the user then the Screen is an environment variable.

**Comment by LesleyWheat** [comment]
> > passed by value
> 
> I see. It's perfect. But I think you should mention what kind of environment variable is. I mean what inData and inLabels are? Those are files?

inData and inLabels aren't files, they are the matrix data type as defined in section 4.

**Comment by LesleyWheat** [comment]
> > 
> 
> I am not sure but the calculation module can generate some kind of exceptions.

Why?

**Comment by LesleyWheat** [comment]
> > Sec
> 
> I have checked your [SRS ](https://github.com/LesleyWheat/CAS741_CEWS/blob/393f285cd50da669a90f6eda17f61ee7b2faaf89/docs/SRS/SRS.pdf) page no -> iii -> Section 1.2 Table of symbols. But I don't find it there. Probably I am wrong.

They are defined in the equations where they are calculated, it would be a lot to put in the table but I could add them.

**Comment by LesleyWheat** [comment]
> > 
> 
> I see. As per your MG, your Graph module constructs the graph at the end. Even your MIS transition phase says that it will construct a graph. So, how are you going to show it at the end? If you are exporting your graph to the system then the File can be an Environment variable and if you are going to show your graph to the user then the Screen is an environment variable.

I'm not going to show or export the graph. Does it say somewhere that it is going to be (I don't remember writing that it does but if it was put in by mistake then I'll need to correct it)?
