### ISSUE TITLE
MG review - items

### ISSUE THREAD

**Issue by joedf** [LesleyWheat/CAS741_CEWS#35]
⚠ **DISCLAIMER / EDIT** : I think I misunderstood "graph" as a visual Cartesian graph/plot and not a node/connection-type graph... If so, maybe say "neighbouring" or something in the description - to reduce confusion/ambiguity from just the word "graph".

- [x] in abbrv. section: "CEWS System | Explanation of program name", I think this was missed, maybe you meant to expand on what CEWS stands for?
- [x] suggestion for Control module secret. maybe mention it handles the "overall" execution.
- in traceability tables:
  - [x] list modules in increasing number order if possible
  - [ ] why both M3 (input) and M6 (graph) map to AC3 ? Isn't it just M6 maybe? Is it because the inputs are displayed on the graph as well?
  - [ ] Why isn't M5 (calculation) as listed for AC5 (gpu vs. cpu) ? this calculation can't be done on GPU?

Otherwise, looks good to me! Short and simple. 👍

**Comment by LesleyWheat** [comment]
I wrote up a new section:
8.1 Explanation of Anticipated changes impacting multiple modules
• AC3: Additional input options would be passed through M2 and validated by M3 then
implemented by M6.
• AC4: Additional input options would be passed through M2 and validated by M3 then
implemented by M6.
• AC5: GPU use indicates a hardware change, impacting M1, and it may require a
change in the algorithm used by M6 so it is optimized for GPU use.
• AC7: Additional input options would be passed through M2 then processed by M3.

Hopefully that answers point 4. M5 doesn't preform the parallelizable part of the calculation (only the graph construction can be parallelized) thus it would not be faster on a GPU,
