### ISSUE TITLE
MIS Review - items

### ISSUE THREAD

**Issue by joedf** [LesleyWheat/CAS741_CEWS#36]
- [x] in the Introduction: the SRS link is provided instead, not the "full documentation and implementation" link which would be, this no?: https://github.com/LesleyWheat/CAS741_CEWS
- [x] in section 6.4.3: are the assumptions (about input) needed ? aren't these issue handled by the input module?
- [x] in section 6.4.4 (maybe for other modules as well?): suggestion - I think you can state the parameters as well like a function declaration:
  - ex: `cutEdgeWeight(inData, inLabels)` instead of just `cutEdgeWeight()` ?
- [ ] section 8, does the verifyOutput really have no output, not even a true or false for valid/pass? or is it just continue running until an error/exception is thrown or completion - kind of thing?
- [x] I don't see the "natural number N" type used anywhere, maybe you can just remove it then? (I likely got extra ones in mine as well or missing some 😅)
- [ ] in section 7.4.3: is the assumption needed? Is it not the job of the input module itself to check if the data is valid, e.g. such length matches... **However**, if this is about whether or the two are related or not as given by the user, than isn't that handled by the SRS?
- [x] in 7.4.4 exceptions: "Any index inData or inLabels is empty" just confirming that you meant "undefined" and not `0`, correct?
- [ ] in 8.4.3: Maybe the assumption is not needed: should it assume that J<sub>N</sub> comes from the Calc. module? As it's own module, shouldn't it work for any given valid value?

**Comment by LesleyWheat** [comment]
> in section 6.4.3: are the assumptions (about input) needed ? aren't these issue handled by the input module?

If the function only got 1 out of 2 inputs then it would raise an error. But the formatting one is covered later (not all formatting problems can be detected) so that is why input has both formatError and assumptions about formatting. I'll remove it from control tho.

**Comment by LesleyWheat** [comment]
> section 8, does the verifyOutput really have no output, not even a true or false for valid/pass? or is it just continue running until an error/exception is thrown or completion - kind of thing?

I thought about it having an output but it seems redundant. ATM it's throwing an exception if the condition isn't met it seems weird to have it pass an output to the control module just for the control module to throw an exception...

**Comment by LesleyWheat** [comment]
> I don't see the "natural number N" type used anywhere, maybe you can just remove it then? (I likely got extra ones in mine as well or missing some 😅)

Oh I was going to leave that in for the matrix sizes but I forgot, I'll just take it out.

**Comment by LesleyWheat** [comment]
>  in section 7.4.3: is the assumption needed? Is it not the job of the input module itself to check if the data is valid, e.g. such length matches... However, if this is about whether or the two are related or not as given by the user, than isn't that handled by the SRS?

Is that not what the assumptions are for? Assuming that the user has done something?

**Comment by LesleyWheat** [comment]
> in 7.4.4 exceptions: "Any index inData or inLabels is empty" just confirming that you meant "undefined" and not 0, correct?

I meant as in empty (or NULL) but it could be defined type (like in python you can create an empty list []) so that's why. 0s are ok for exceptions but if you passed 0, 0 (I need to add an exception for less than two classes actually so different problem). 0s in a vector are ok.

**Comment by LesleyWheat** [comment]
> in 8.4.3: Maybe the assumption is not needed: should it assume that JN comes from the Calc. module? As it's own module, shouldn't it work for any given valid value?

I guess but does it make sense not to have it? Like it is designed to check J_N specifically, not just any random number and it would work but the output wouldn't make much sense. Like it is checking the constraints specifically for J_N, not just a generic output.
