### ISSUE TITLE
SRS Review: Provide an example of a physical system to be modelled

### ISSUE THREAD

**Issue by samm82** [LesleyWheat/CAS741_CEWS#7]
For the Physical System Description section, while there isn't one physical system that this program models, I think it would be useful to provide an example, like you did in class with "shirt colour" and "height", of the types of physical systems that can be modelled.

**Comment by LesleyWheat** [comment]
The SRS is not required to introduce to reader of the SRS to the general concepts of classification, this is covered under Characteristics of Intended Reader.
